config ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i_cfg;
		design ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i;
		instance ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i.ioaux_master_bridge use ddr4_core_altera_avalon_mm_bridge_161.altera_avalon_mm_bridge;
		instance ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i.ioaux_soft_ram use ddr4_core_altera_avalon_onchip_memory2_161.ddr4_core_altera_avalon_onchip_memory2_161_ouhlr2a;
		instance ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i.mm_interconnect_0 use ddr4_core_altera_mm_interconnect_161.ddr4_core_altera_mm_interconnect_161_rjywn6y;
		instance ddr4_core_altera_emif_cal_slave_nf_161_m6azz7i.rst_controller use ddr4_core_altera_reset_controller_161.altera_reset_controller;
endconfig

