config ddr4_core_altera_mm_interconnect_161_x5yuuaa_cfg;
		design ddr4_core_altera_mm_interconnect_161_x5yuuaa;
		instance ddr4_core_altera_mm_interconnect_161_x5yuuaa.colmaster_master_translator use ddr4_core_altera_merlin_master_translator_161.altera_merlin_master_translator;
		instance ddr4_core_altera_mm_interconnect_161_x5yuuaa.avl_bridge_out_s0_translator use ddr4_core_altera_merlin_slave_translator_161.altera_merlin_slave_translator;
endconfig

