config ddr4_core_altera_mm_interconnect_161_wl6t3li_cfg;
		design ddr4_core_altera_mm_interconnect_161_wl6t3li;
		instance ddr4_core_altera_mm_interconnect_161_wl6t3li.col_if_to_ioaux_translator use ddr4_core_altera_merlin_master_translator_161.altera_merlin_master_translator;
		instance ddr4_core_altera_mm_interconnect_161_wl6t3li.arch_cal_debug_translator use ddr4_core_altera_merlin_slave_translator_161.altera_merlin_slave_translator;
endconfig

