config ddr4_core_altera_mm_interconnect_161_rjywn6y_cfg;
		design ddr4_core_altera_mm_interconnect_161_rjywn6y;
		instance ddr4_core_altera_mm_interconnect_161_rjywn6y.ioaux_master_bridge_m0_translator use ddr4_core_altera_merlin_master_translator_161.altera_merlin_master_translator;
		instance ddr4_core_altera_mm_interconnect_161_rjywn6y.ioaux_soft_ram_s1_translator use ddr4_core_altera_merlin_slave_translator_161.altera_merlin_slave_translator;
endconfig

