// fp_sub_d.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module fp_sub_d (
		input  wire [31:0] a,      //      a.a
		input  wire        areset, // areset.reset
		input  wire [31:0] b,      //      b.b
		input  wire        clk,    //    clk.clk
		output wire [31:0] q       //      q.q
	);

	fp_sub_d_altera_fp_functions_161_se3ntfy fp_functions_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.b      (b),      //      b.b
		.q      (q)       //      q.q
	);

endmodule
