// fifo_M.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module fifo_M (
		input  wire [31:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq(ack)
		input  wire        clock, //            .clk
		input  wire        aclr,  //            .aclr
		output wire [31:0] q,     // fifo_output.dataout
		output wire [11:0] usedw  //            .usedw
	);

	fifo_M_fifo_161_skz73ra fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq(ack)
		.clock (clock), //            .clk
		.aclr  (aclr),  //            .aclr
		.q     (q),     // fifo_output.dataout
		.usedw (usedw)  //            .usedw
	);

endmodule
