// ram_2048x512_8192x128.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module ram_2048x512_8192x128 (
		input  wire [511:0] data,      //  ram_input.datain
		input  wire [10:0]  wraddress, //           .wraddress
		input  wire [12:0]  rdaddress, //           .rdaddress
		input  wire         wren,      //           .wren
		input  wire         wrclock,   //           .wrclock
		input  wire         rdclock,   //           .rdclock
		input  wire         rden,      //           .rden
		output wire [127:0] q          // ram_output.dataout
	);

	ram_2048x512_8192x128_ram_2port_161_himwlxy ram_2port_0 (
		.data      (data),      //  ram_input.datain
		.wraddress (wraddress), //           .wraddress
		.rdaddress (rdaddress), //           .rdaddress
		.wren      (wren),      //           .wren
		.wrclock   (wrclock),   //           .wrclock
		.rdclock   (rdclock),   //           .rdclock
		.rden      (rden),      //           .rden
		.q         (q)          // ram_output.dataout
	);

endmodule
