config ddr4_core_alt_mem_if_jtag_master_161_s34bviy_cfg;
		design ddr4_core_alt_mem_if_jtag_master_161_s34bviy;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.jtag_phy_embedded_in_jtag_master use ddr4_core_altera_jtag_dc_streaming_161.altera_avalon_st_jtag_interface;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.timing_adt use ddr4_core_timing_adapter_161.ddr4_core_timing_adapter_161_u532i6q;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.fifo use ddr4_core_altera_avalon_sc_fifo_161.altera_avalon_sc_fifo;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.b2p use ddr4_core_altera_avalon_st_bytes_to_packets_161.altera_avalon_st_bytes_to_packets;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.p2b use ddr4_core_altera_avalon_st_packets_to_bytes_161.altera_avalon_st_packets_to_bytes;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.transacto use ddr4_core_altera_avalon_packets_to_master_161.altera_avalon_packets_to_master;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.b2p_adapter use ddr4_core_channel_adapter_161.ddr4_core_channel_adapter_161_fcviibi;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.p2b_adapter use ddr4_core_channel_adapter_161.ddr4_core_channel_adapter_161_xd7xncy;
		instance ddr4_core_alt_mem_if_jtag_master_161_s34bviy.rst_controller use ddr4_core_altera_reset_controller_161.altera_reset_controller;
endconfig

