// afifo_8x1.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module afifo_8x1 (
		input  wire       data,    //  fifo_input.datain
		input  wire       wrreq,   //            .wrreq
		input  wire       rdreq,   //            .rdreq
		input  wire       wrclk,   //            .wrclk
		input  wire       rdclk,   //            .rdclk
		output wire       q,       // fifo_output.dataout
		output wire [2:0] wrusedw, //            .wrusedw
		output wire       rdempty, //            .rdempty
		output wire       wrfull   //            .wrfull
	);

	afifo_8x1_fifo_161_rgwi5iq fifo_0 (
		.data    (data),    //  fifo_input.datain
		.wrreq   (wrreq),   //            .wrreq
		.rdreq   (rdreq),   //            .rdreq
		.wrclk   (wrclk),   //            .wrclk
		.rdclk   (rdclk),   //            .rdclk
		.q       (q),       // fifo_output.dataout
		.wrusedw (wrusedw), //            .wrusedw
		.rdempty (rdempty), //            .rdempty
		.wrfull  (wrfull)   //            .wrfull
	);

endmodule
