for i in range (0,6) :
	print("//-------------------------------s%d------------------------------//"%(i))

	print("reg        matrix_memory_sop_%d ;" %(i))
	print("reg        matrix_memory_eop_%d ;" %(i))
	print("reg        matrix_memory_vld_%d ;" %(i))
	print("reg [31:0] matrix_memory_data_%d;" %(i))
	print("reg [31:0] M_write_%d           ;"%(i))
	print("reg [31:0] X_write_%d            ;"%(i))
	print("reg        vld_%d 				;"%(i))
	print("reg 	   init_out_%d 			;"%(i))
	print("")
	print("wire         pkt_receive_enable_%d;"%(i))
	print("wire [ 31:0] ram_out_%d           ;"%(i))
	print("wire [  7:0] q_%d                 ;"%(i))
	print("wire [  7:0] i_%d                 ;"%(i))
	print("wire [  7:0] R_%d                 ;"%(i))
	print("wire [  7:0] H_%d                 ;"%(i))
	print("wire [ 31:0] M_read_%d            ;"%(i))
	print("wire [ 31:0] X_read_%d            ;"%(i))
	print("wire         parameter_vld_%d     ;"%(i))
	print("wire         en_sum_%d            ;"%(i))
	print("wire         mode_%d              ;"%(i))
	print("wire         sum_select_%d        ;"%(i))
	print("wire         sum_vld_%d           ;"%(i))
	print("wire [ 31:0] y_initial_%d         ;"%(i))
	print("wire         init_%d              ;"%(i))
	print("wire [ 63:0] head_%d              ;"%(i))
	print("wire [  5:0] pe_cnt_%d 			 ;"%(i))

# for i in range (0,8):
# 	print("reg [31:0] pmx_5_%d    ;"%(i))
# 	print("reg [31:0] pmy_5_%d    ;"%(i))
# 	print("reg [31:0] pmm_5_%d    ;"%(i))
# 	print("reg [31:0] lambda0_5_%d;"%(i))
# 	print("reg [31:0] lambda1_5_%d;"%(i))
# 	print("reg [ 7:0] r_in_5_%d   ;"%(i))
# 	print("")



# for i in range (0,6):
# 	print("always @(posedge sys_clk or negedge sys_rst_n)")
# 	print("begin ")
# 	print("	   	if (!sys_rst_n) begin	")
# 	print("			vld_%d <= 1'b0;"%(i))
# 	print(" 	end else if (shift_reg == S%d) begin"%(i))
# 	print("			vld_%d <= 1'b1;" %(i))
# 	print("		end else if (shift_reg == S%d) begin"%(i+1))
# 	print("			vld_%d <= 1'b0;"%(i))
# 	print("		end")
# 	print("end")
