// rom_256x32.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module rom_256x32 (
		input  wire [7:0]  address, //  rom_input.address
		input  wire        clock,   //           .clk
		input  wire        rden,    //           .rden
		output wire [35:0] q        // rom_output.dataout
	);

	rom_256x32_rom_1port_161_n3fz64y rom_1port_0 (
		.address (address), //  rom_input.address
		.clock   (clock),   //           .clk
		.rden    (rden),    //           .rden
		.q       (q)        // rom_output.dataout
	);

endmodule
