config ddr4_core_altera_ip_col_if_161_foc7v3q_cfg;
		design ddr4_core_altera_ip_col_if_161_foc7v3q;
		instance ddr4_core_altera_ip_col_if_161_foc7v3q.avl_bridge_out use ddr4_core_altera_avalon_mm_bridge_161.altera_avalon_mm_bridge;
		instance ddr4_core_altera_ip_col_if_161_foc7v3q.colmaster use ddr4_core_alt_mem_if_jtag_master_161.ddr4_core_alt_mem_if_jtag_master_161_s34bviy;
		instance ddr4_core_altera_ip_col_if_161_foc7v3q.mm_interconnect_0 use ddr4_core_altera_mm_interconnect_161.ddr4_core_altera_mm_interconnect_161_x5yuuaa;
endconfig

