// pll_125m.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module pll_125m (
		output wire  locked,   //  locked.export
		output wire  outclk_0, // outclk0.clk
		input  wire  refclk,   //  refclk.clk
		input  wire  rst       //   reset.reset
	);

	pll_125m_altera_iopll_161_5zboggi iopll_0 (
		.rst      (rst),      //   reset.reset
		.refclk   (refclk),   //  refclk.clk
		.locked   (locked),   //  locked.export
		.outclk_0 (outclk_0)  // outclk0.clk
	);

endmodule
