// ddr4_core_altera_mm_interconnect_161_wl6t3li.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module ddr4_core_altera_mm_interconnect_161_wl6t3li (
		input  wire        arch_cal_master_clk_clk,                       //                     arch_cal_master_clk.clk
		input  wire        col_if_avl_rst_in_reset_bridge_in_reset_reset, // col_if_avl_rst_in_reset_bridge_in_reset.reset
		input  wire [29:0] col_if_to_ioaux_address,                       //                         col_if_to_ioaux.address
		output wire        col_if_to_ioaux_waitrequest,                   //                                        .waitrequest
		input  wire [0:0]  col_if_to_ioaux_burstcount,                    //                                        .burstcount
		input  wire [3:0]  col_if_to_ioaux_byteenable,                    //                                        .byteenable
		input  wire        col_if_to_ioaux_read,                          //                                        .read
		output wire [31:0] col_if_to_ioaux_readdata,                      //                                        .readdata
		output wire        col_if_to_ioaux_readdatavalid,                 //                                        .readdatavalid
		input  wire        col_if_to_ioaux_write,                         //                                        .write
		input  wire [31:0] col_if_to_ioaux_writedata,                     //                                        .writedata
		input  wire        col_if_to_ioaux_debugaccess,                   //                                        .debugaccess
		output wire [23:0] arch_cal_debug_address,                        //                          arch_cal_debug.address
		output wire        arch_cal_debug_write,                          //                                        .write
		output wire        arch_cal_debug_read,                           //                                        .read
		input  wire [31:0] arch_cal_debug_readdata,                       //                                        .readdata
		output wire [31:0] arch_cal_debug_writedata,                      //                                        .writedata
		output wire [3:0]  arch_cal_debug_byteenable,                     //                                        .byteenable
		input  wire        arch_cal_debug_readdatavalid,                  //                                        .readdatavalid
		input  wire        arch_cal_debug_waitrequest                     //                                        .waitrequest
	);

	wire         col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest;   // arch_cal_debug_translator:uav_waitrequest -> col_if_to_ioaux_translator:uav_waitrequest
	wire  [31:0] col_if_to_ioaux_translator_avalon_universal_master_0_readdata;      // arch_cal_debug_translator:uav_readdata -> col_if_to_ioaux_translator:uav_readdata
	wire         col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess;   // col_if_to_ioaux_translator:uav_debugaccess -> arch_cal_debug_translator:uav_debugaccess
	wire  [31:0] col_if_to_ioaux_translator_avalon_universal_master_0_address;       // col_if_to_ioaux_translator:uav_address -> arch_cal_debug_translator:uav_address
	wire         col_if_to_ioaux_translator_avalon_universal_master_0_read;          // col_if_to_ioaux_translator:uav_read -> arch_cal_debug_translator:uav_read
	wire   [3:0] col_if_to_ioaux_translator_avalon_universal_master_0_byteenable;    // col_if_to_ioaux_translator:uav_byteenable -> arch_cal_debug_translator:uav_byteenable
	wire         col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid; // arch_cal_debug_translator:uav_readdatavalid -> col_if_to_ioaux_translator:uav_readdatavalid
	wire         col_if_to_ioaux_translator_avalon_universal_master_0_lock;          // col_if_to_ioaux_translator:uav_lock -> arch_cal_debug_translator:uav_lock
	wire         col_if_to_ioaux_translator_avalon_universal_master_0_write;         // col_if_to_ioaux_translator:uav_write -> arch_cal_debug_translator:uav_write
	wire  [31:0] col_if_to_ioaux_translator_avalon_universal_master_0_writedata;     // col_if_to_ioaux_translator:uav_writedata -> arch_cal_debug_translator:uav_writedata
	wire   [2:0] col_if_to_ioaux_translator_avalon_universal_master_0_burstcount;    // col_if_to_ioaux_translator:uav_burstcount -> arch_cal_debug_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (30),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (0),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) col_if_to_ioaux_translator (
		.clk                    (arch_cal_master_clk_clk),                                            //                       clk.clk
		.reset                  (col_if_avl_rst_in_reset_bridge_in_reset_reset),                      //                     reset.reset
		.uav_address            (col_if_to_ioaux_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (col_if_to_ioaux_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (col_if_to_ioaux_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (col_if_to_ioaux_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (col_if_to_ioaux_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (col_if_to_ioaux_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (col_if_to_ioaux_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (col_if_to_ioaux_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (col_if_to_ioaux_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (col_if_to_ioaux_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (col_if_to_ioaux_burstcount),                                         //                          .burstcount
		.av_byteenable          (col_if_to_ioaux_byteenable),                                         //                          .byteenable
		.av_read                (col_if_to_ioaux_read),                                               //                          .read
		.av_readdata            (col_if_to_ioaux_readdata),                                           //                          .readdata
		.av_readdatavalid       (col_if_to_ioaux_readdatavalid),                                      //                          .readdatavalid
		.av_write               (col_if_to_ioaux_write),                                              //                          .write
		.av_writedata           (col_if_to_ioaux_writedata),                                          //                          .writedata
		.av_debugaccess         (col_if_to_ioaux_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1),                                                               //               (terminated)
		.uav_response           (2'b00),                                                              //               (terminated)
		.av_response            (),                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                    //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (24),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) arch_cal_debug_translator (
		.clk                    (arch_cal_master_clk_clk),                                            //                      clk.clk
		.reset                  (col_if_avl_rst_in_reset_bridge_in_reset_reset),                      //                    reset.reset
		.uav_address            (col_if_to_ioaux_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (col_if_to_ioaux_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (col_if_to_ioaux_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (col_if_to_ioaux_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (col_if_to_ioaux_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (col_if_to_ioaux_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (col_if_to_ioaux_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (col_if_to_ioaux_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (arch_cal_debug_address),                                             //      avalon_anti_slave_0.address
		.av_write               (arch_cal_debug_write),                                               //                         .write
		.av_read                (arch_cal_debug_read),                                                //                         .read
		.av_readdata            (arch_cal_debug_readdata),                                            //                         .readdata
		.av_writedata           (arch_cal_debug_writedata),                                           //                         .writedata
		.av_byteenable          (arch_cal_debug_byteenable),                                          //                         .byteenable
		.av_readdatavalid       (arch_cal_debug_readdatavalid),                                       //                         .readdatavalid
		.av_waitrequest         (arch_cal_debug_waitrequest),                                         //                         .waitrequest
		.av_begintransfer       (),                                                                   //              (terminated)
		.av_beginbursttransfer  (),                                                                   //              (terminated)
		.av_burstcount          (),                                                                   //              (terminated)
		.av_writebyteenable     (),                                                                   //              (terminated)
		.av_lock                (),                                                                   //              (terminated)
		.av_chipselect          (),                                                                   //              (terminated)
		.av_clken               (),                                                                   //              (terminated)
		.uav_clken              (1'b0),                                                               //              (terminated)
		.av_debugaccess         (),                                                                   //              (terminated)
		.av_outputenable        (),                                                                   //              (terminated)
		.uav_response           (),                                                                   //              (terminated)
		.av_response            (2'b00),                                                              //              (terminated)
		.uav_writeresponsevalid (),                                                                   //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                //              (terminated)
	);

endmodule
