// fifo_512x32.v

// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module fifo_512x32 (
		input  wire [31:0] data,  //  fifo_input.datain
		input  wire        wrreq, //            .wrreq
		input  wire        rdreq, //            .rdreq(ack)
		input  wire        clock, //            .clk
		input  wire        aclr,  //            .aclr
		output wire [31:0] q,     // fifo_output.dataout
		output wire [8:0]  usedw, //            .usedw
		output wire        full,  //            .full
		output wire        empty  //            .empty
	);

	fifo_512x32_fifo_161_6hroaea fifo_0 (
		.data  (data),  //  fifo_input.datain
		.wrreq (wrreq), //            .wrreq
		.rdreq (rdreq), //            .rdreq(ack)
		.clock (clock), //            .clk
		.aclr  (aclr),  //            .aclr
		.q     (q),     // fifo_output.dataout
		.usedw (usedw), //            .usedw
		.full  (full),  //            .full
		.empty (empty)  //            .empty
	);

endmodule
